### ISSUE TITLE
Rooms die level in transition.

### ISSUE THREAD

**Issue by ViezeVingertjes** [kasami/kasamibot#3]
Rooms that are going to build the storage, will die most of the time due to an empty container and are not able to rebuild with expansionWorkers that are sent. This is most likely due to the builders, that are building the storage while standing between the container and the storage construction site. They drain all the energy and creeps can't be spawned due to a shortage.

**Comment by kasami** [comment]
Yeah, I've seen it happend a few times. Will try to tweak it, so to transition between container->storage is less prone for errors.
