### ISSUE TITLE
After abandon room is in limbo.

### ISSUE THREAD

**Issue by ViezeVingertjes** [kasami/kasamibot#4]
When you leave a room, it might be targetted for expansion (automated or manually) again. Yet, it believes there is a spawn present while there isnt. Tries to spawn without a spawn resulting in errors.

**Comment by kasami** [comment]
Yeah, that's a bug that I'll fix.

As a temporary fix, remove the value "isBeingDismantled" from the room memory of the room that does not build.

The fix will basically remove isBeingDismantled from unowned rooms and expansions. It prevents any building from happening.
