### ISSUE TITLE
Code Still Accessible

### ISSUE THREAD

**Issue by ndbeals** [kasami/kasamibot#9]
Hello!

I saw you removed the code from public access, which is probably good. However it's still accessible by looking a commit back.(https://github.com/kasami/kasamibot/tree/6830e7be851385249ad53cac5aaf259fad2b60e6)

I don't know enough about git offhand to tell you how to fix it, but I know it is fixable, I think.

**Comment by opt-bouvet** [comment]
Yeah, I know. I wanted to make it harder to find it, but people who know git will be able to get the code. (it is available on about 15 forks as well)
It is also still available on npm, but removed from steam workshop.

So far it looks like the amount of new ppl using it has slowed down, so I'll keep it that way. Most new ppl probably found it in the workshop.

**Comment by kasami** [comment]
Yeah, I know. I wanted to make it harder to find it, but people who know git will be able to get the code. (it is available on about 15 forks as well)
It is also still available on npm, but removed from steam workshop.

So far it looks like the amount of new ppl using it has slowed down, so I'll keep it that way. Most new ppl probably found it in the workshop.
